# $HOME/.config/alacritty/alacritty.toml

[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
normal = {family = "AdwaitaMono Nerd Font Propo", style = "Regular"}
bold = {family = "AdwaitaMono Nerd Font Propo", style = "Bold"}
italic = {family = "AdwaitaMono Nerd Font Propo", style = "Italic"}
bold_italic = {family = "AdwaitaMono Nerd Font Propo", style = "Bold Italic"}
size = 12.0